### ISSUE TITLE
Last letter space bug

### ISSUE THREAD

**Issue by Mecanik** [marek-saji/po-csv#10]
Consider the following:

`msgid "Invalid reset key or it may have expired. Please return "`

The CSV will be converted without the last space.

Thanks

**Comment by marek-saji** [comment]
@Mecanik Could you include an example input PO file? I could not replicate the bug.

**Comment by marek-saji** [comment]
I’m doing some cleaning up in the project. I created test with the `msgid` you gavem but they pass, so I’m closing this issue. Please open a new one and provide example failing file if you still have the problem.
