### ISSUE TITLE
Bug - cant open translated files

### ISSUE THREAD

**Issue by goranGG** [marek-saji/po-csv#17]
### What happened?

node version 18.17
npm version 9.8.1
Windows + powershell

I used input PO file from tests\main and used these two commands, same result I am getting when I use some other PO files
npx po-csv .\tests\main\input.po > input-main.csv
npx po-csv .\input-main.csv > translated-csv.po

cant upload po file so i change extension to txt

but file translated-csv.po is empty inside, is there something I am missing or?
[input-main.csv](https://github.com/marek-saji/po-csv/files/12144939/input-main.csv)
[translated-csv.txt](https://github.com/marek-saji/po-csv/files/12144947/translated-csv.txt)

I tried to reinstall everything now I just get 
'pocsv' is not recognized as an internal or external command,
operable program or batch file.
and empty input-main.csv

**Comment by marek-saji** [comment]
> I used input PO file from tests\main and used these two commands, same result I am getting when I use some other PO files
> npx po-csv .\tests\main\input.po > input-main.csv
> npx po-csv .\input-main.csv > translated-csv.po

When converting CSV back to PO, you need to give it two arguments: old PO file and CSV translations. CSV doesn’t include all of the information, so we need a place to get them from:

```
npx po-csv .\tests\main\input.po > input-main.csv
npx po-csv .\tests\main\input.po .\input-main.csv > translated-csv.po
```

**Comment by marek-saji** [comment]
Feel free to re–open the bug if you have any more problems. :slightly_smiling_face:
