### ISSUE TITLE
Bug - Conversion to CSV replaces "\n" characters with new lines

### ISSUE THREAD

**Issue by matheusandradepinto** [marek-saji/po-csv#18]
### What happened?

Hey, first of all - thanks for the tool, it's a massive improvement over the translate-toolkit packages when it comes to .po files :)

One issue I have found is that the tool seems to replace "\n" characters in source (msgid) and target (msgstr) text, I've played around with a few .po files and that seems to always happen.

Is there a way to prevent it from doing that in occurrences where that is unintended behaviour?

Cheers!

**Comment by marek-saji** [comment]
Please provide an example .po file for which it happens. Ideally along with .csv that you’d like to be produced by `po-csv your-file.po`.

**Comment by marek-saji** [comment]
Closing due to no response. Feel free to re–open it and attach file(s) that are causing problems.
