### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by jziggas** [marek-saji/po-csv#2]
```
node_modules/po-csv/index.js:98
    .concat(new Array (nplurals - item.msgstr.length).join('.').split('.'))
```

**Comment by jziggas** [comment]
Found the problem object:

```
{
  "msgid": "1 Topic",
  "msgctxt": null,
  "references": ["path\/to\/template.html:15"],
  "msgid_plural": "{{$count}} Topics",
  "msgstr": ["", ""],
  "comments": [],
  "extractedComments": [],
  "flags": {},
  "obsolete": false
}
```

which is causing `new Array (nplurals - item.msgstr.length)` on line ~98 to try and make an Array with length of `-1` where `nplurals === 1` and `item.msgstr.length === 2`.

My template.pot file is created from gulp-angular-gettext.

HTML:

```
<span translate translate-n="threads.length" translate-plural="{{$count}} Topics">1 Topic</span>
```

**Comment by jziggas** [comment]
Alright last comment of the day ;) I figured out that this is happening because po-csv expects a PO file with plural information in the file header. And POT files don't have that information yet because the POT file hasn't been translated and merged into a PO file yet.

**Comment by marek-saji** [comment]
@jziggas Thanks for reporting the bug. 😃 Sorry it took so long to fix.
